common: &common
  adapter: postgresql
  host: localhost
development:
  <<: *common
  database: mysquash_dev

test:
  <<: *common
  database: mysquash_test

production:
  <<: *common
  database: mysquash_prod