common: &common
  adapter: postgresql
  host: localhost
development:
  <<: *common
  database: mysquash_dev

test:
  <<: *common
  database: mysquash_test

production:
  adapter: mysql2
  encoding: utf8
  host: localhost
  database: info
  username: info
  password: aSYafUT2j57YM2mJ
